version: '3'

services:
  web:
    build: ./
    command: python src/manage.py runserver 0.0.0.0:8000 --settings app.devel_settings
    volumes:
      - ./src/:/usr/app/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
